"""
Pipeline plugin interface.

Plugins are primarily build-time — they enrich source definitions, automapping
tables, and generate ConceptMaps. They do NOT perform runtime source data
transforms so that the generated StructureMaps + ConceptMaps remain
self-contained and portable to any FHIR server that supports $transform.

One runtime hook exists (``post_bundle``), constrained by the same principle:
it may only AUGMENT an assembled output bundle with additional metadata
resources (e.g. Provenance records for lineage), never modify the transformed
content itself — removing the plugin must leave transform output semantically
identical, minus the metadata.

To implement a plugin:
  1. Subclass PipelinePlugin.
  2. Override whichever hooks are relevant (all default to no-op pass-through).
  3. Register the class in the plugin registry or set "type" in the project config.

Configuration (in project JSON):
  "plugins": [
    { "type": "redcap", "source": "api", ... },
    { "type": "my_custom_plugin", "custom_key": "value" }
  ]
"""

from abc import ABC, abstractmethod
from typing import Optional


class PipelinePlugin(ABC):
    """Base class for all pipeline plugins."""

    def __init__(self, config: dict):
        """
        :param config: The plugin's configuration block from the project config.
        """
        self.config = config

    @property
    @abstractmethod
    def plugin_id(self) -> str:
        """Unique identifier string, e.g. 'redcap', 'omop', 'hl7v2'."""

    # ── build-time hooks ──────────────────────────────────────────────────────

    def post_source_def(
        self,
        source_definition: dict,
        source_fields: list[dict],
    ) -> dict:
        """
        Hook 1 — called after the source StructureDefinition has been generated.

        Use this to enrich field metadata: descriptions from a codebook, data-type
        hints from a platform schema, ValueSet bindings inferred from platform
        metadata, etc.

        :param source_definition: The generated FHIR StructureDefinition dict.
        :param source_fields: The flat list of source field dicts used during
                              source-def generation (each has 'id', 'path',
                              'description').
        :returns: The (possibly modified) source_definition dict.
        """
        return source_definition

    def enrich_automapping(self, automapping: dict[str, str]) -> dict[str, str]:
        """
        Hook 2 — called after the automapping table is loaded/built but before
        StructureMap generation.

        Use this to add missing mappings or correct wrong ones derived from
        platform-specific knowledge (e.g. a codebook annotation that states
        field X always maps to FHIR path Y).

        :param automapping: Dict of {source_field_id: fhir_target_path}.
        :returns: The enriched automapping dict.
        """
        return automapping

    def generate_concept_map(
        self,
        field_name: str,
        field_meta: dict,
        existing_cm: Optional[dict],
    ) -> Optional[dict]:
        """
        Hook 3 — called for each coded source field during StructureMap generation
        when a ConceptMap is needed.

        The plugin can return a FHIR ConceptMap dict to supplement or replace the
        auto-generated one, or None to use the auto-generated CM unchanged.

        :param field_name: The source field name (e.g. 'aktbefinden').
        :param field_meta: Platform-specific metadata for this field (choices,
                           annotations, validation type, etc.) as returned by
                           the codebook reader.
        :param existing_cm: The ConceptMap already generated by the static
                            generator, or None if none was generated.
        :returns: A FHIR ConceptMap dict, or None to leave the existing CM.
        """
        return None

    # ── runtime hooks ─────────────────────────────────────────────────────────

    def post_bundle(self, bundle: dict, context: dict) -> dict:
        """
        Hook 4 — called after a transaction Bundle has been assembled from
        transform output, before it is returned/shipped.

        AUGMENTATION ONLY: add metadata entries (e.g. Provenance, Device);
        never modify or remove the transformed resources themselves — the
        bundle without the plugin must remain semantically identical minus
        the added metadata.

        :param bundle: The assembled FHIR transaction Bundle dict.
        :param context: Runtime context:
                        'source_record' — the flat source object this bundle
                                          was transformed from (None if the
                                          caller could not associate one),
                        'structure_maps' — list of StructureMap dicts used.
        :returns: The (possibly augmented) bundle dict.
        """
        return bundle

    def get_field_metadata(self, field_name: str) -> Optional[dict]:
        """
        Return platform metadata for a specific field if available.
        Used by the pipeline to query this plugin before calling
        generate_concept_map.  Override to provide lookup.
        """
        return None
