id: synthladder
canonical: http://example.org/synthladder
name: SynthLadder
status: draft
version: 0.1.0
fhirVersion: 4.0.1
copyrightYear: 2026+
releaseLabel: ci-build
FSHOnly: false
applyExtensionMetadataToRoot: false
