id: motu.recreation
canonical: http://ahdbservices.it
name: MotuRecreation
status: draft
version: 0.1.0
fhirVersion: 4.0.1
copyrightYear: 2026+
releaseLabel: ci-build
publisher:
  name: MOTU recreation (E10)
